import React from 'react'
import ReactDOM from 'react-dom/client'
import App from "./App";
import './App.css'
import './assets/fonts/Bizmo/Bizmo-Bold.ttf'
import './assets/fonts/Clara/Clara.ttf'
import './assets/fonts/Clara/Clara-Strip.ttf'
import './assets/fonts/Bronson/Bronson-Black.ttf'
import './assets/fonts/Leemu/Leemu_Demo.ttf'
import './assets/fonts/Espirit/Esprit.ttf'
import './assets/fonts/Livemono/Livemono-Regular-Demo.otf'
import './assets/fonts/Mainframe/Mainframe-Regular.ttf'
import './assets/fonts/Metorius/Metorius_Sans_Demo.otf'
import './assets/fonts/Oldtimer/Oldtimer.ttf'
import './assets/fonts/Sherman/Sherman-Display.ttf'
import './assets/fonts/Sherman/Sherman-Italic.ttf'
import './assets/fonts/TT Severs/TT-Severs-Regular.otf'
import './assets/fonts/TT Severs/TT-Severs-Bold.otf'
import './assets/fonts/TT Severs/TT-Severs-Bold-Italic.otf'
import './assets/fonts/TT Severs/TT-Severs-Italic.otf'
import './assets/fonts/TT Severs/TT-Severs-Black.otf'
import './assets/fonts/TT Severs/TT-Severs-Black-Italic.otf'
import './assets/fonts/TT Severs/TT-Severs-Light.otf'
import './assets/fonts/TT Severs/TT-Severs-Light-Italic.otf'
import './assets/fonts/TT Severs/TT-Severs-Medium.otf'
import './assets/fonts/TT Severs/TT-Severs-Medium-Italic.otf'
import './assets/fonts/TT Severs/TT-Severs-DemiBold.otf'
import './assets/fonts/TT Severs/TT-Severs-DemiBold-Italic.otf'
import './assets/fonts/TT Severs/TT-Severs-ExtraBold.otf'
import './assets/fonts/TT Severs/TT-Severs-ExtraBold-Italic.otf'
import './assets/fonts/TT Severs/TT-Severs-ExtraLight.otf'
import './assets/fonts/TT Severs/TT-Severs-ExtraLight-Italic.otf'
import './assets/fonts/TT Severs/TT-Severs-Thin.otf'
import './assets/fonts/TT Severs/TT-Severs-Thin-Italic.otf'

ReactDOM.createRoot(document.getElementById('root') as HTMLElement).render(
    <App/>
)
